language: php

sudo: false

git:
  depth: 1

matrix:
  include:
    - php: 5.5
      env: COMPOSER_FLAGS="--prefer-stable --prefer-lowest"
    - php: 7.0
    - php: 7.1

cache:
  directories:
    - ${HOME}/.composer/cache

before_install:
  - phpenv config-rm xdebug.ini
  - set | grep -E "^(TRAVIS|COMPOSER)" | sort
  - composer validate
  - php -i

install:
  - travis_retry composer update -n -o --no-progress ${COMPOSER_FLAGS}
  - composer info -D > info.txt
  - cat info.txt

script:
  - true
